name: 'Get a cache dependencies'
description: 'Get the dependenices via npm and then cache them'
inputs:
  caching:
    descripiton: 'whether to cache is depend opr not'
    required: true
    default: 'true'
outputs: 
  used-cache:
    description: 'whether the cache is used'
    value: ${{ steps.install.outputs.cache }}
runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      if: inputs.caching == 'true'
      id: cache
      uses: actions/cache@v4
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      run: |
        npm ci
        echo "::set-output name=cache::'${{ inputs.caching }}'"
      shell: bash